spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

jwt:
  secret: pretemoica-ci-secret-key-pretemoica-ci-secret-key-123456
  expiration-ms: 3600000
