DROP TABLE IF EXISTS user_friends CASCADE;
DROP TABLE IF EXISTS app_user_objects CASCADE;
DROP TABLE IF EXISTS lending_history CASCADE;
DROP TABLE IF EXISTS lending CASCADE;
DROP TABLE IF EXISTS object CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS image CASCADE;
DROP TABLE IF EXISTS address CASCADE;

CREATE TABLE image (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       url VARCHAR(255) NOT NULL,
                       file_name VARCHAR(255) NOT NULL,
                       content_type VARCHAR(255),
                       file_size BIGINT
);

CREATE TABLE address (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         street VARCHAR(255) NOT NULL,
                         city VARCHAR(255) NOT NULL,
                         postal_code VARCHAR(255) NOT NULL,
                         country VARCHAR(255) NOT NULL,
                         complement VARCHAR(255),
                         latitude DOUBLE PRECISION,
                         longitude DOUBLE PRECISION
);

CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255),
                          avatar VARCHAR(255),
                          description VARCHAR(1000),
                          first_name VARCHAR(255),
                          last_name VARCHAR(255),
                          profile_image_id BIGINT REFERENCES image(id),
                          address_id BIGINT REFERENCES address(id),
                          rating INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE object (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        description TEXT,
                        weight DOUBLE PRECISION,
                        dimensions VARCHAR(255),
                        owned_by_id BIGINT NOT NULL REFERENCES app_user(id),
                        state_of_wear VARCHAR(32),
                        category VARCHAR(32),
                        material VARCHAR(32),
                        images VARCHAR(2000) DEFAULT '[]'
);

CREATE TABLE app_user_objects (
                                  app_user_id BIGINT NOT NULL REFERENCES app_user(id),
                                  objects_id BIGINT NOT NULL REFERENCES object(id)
);

CREATE TABLE user_friends (
                              user_id BIGINT NOT NULL REFERENCES app_user(id),
                              friend_id BIGINT NOT NULL REFERENCES app_user(id)
);

CREATE TABLE lending (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         borrowed_by_id BIGINT NOT NULL REFERENCES app_user(id),
                         offered_by_id BIGINT NOT NULL REFERENCES app_user(id),
                         object_id BIGINT NOT NULL REFERENCES object(id),
                         status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
                         started_at TIMESTAMP,
                         ended_at TIMESTAMP
);

CREATE TABLE lending_history (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 borrowed_by_id BIGINT NOT NULL REFERENCES app_user(id),
                                 offered_by_id BIGINT NOT NULL REFERENCES app_user(id),
                                 object_id BIGINT NOT NULL REFERENCES object(id),
                                 status VARCHAR(32),
                                 started_at TIMESTAMP,
                                 ended_at TIMESTAMP
);