spring:
  application:
    name: pretemoica
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:projetPret}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidation12345}
  expiration: ${JWT_EXPIRATION:86400000}



