app:
  upload:
    dir : ./uploads
    public-path: /uploads



spring:
  application:
    name: pretemoica
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:projetPret}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidation12345}
  expiration: ${JWT_EXPIRATION:86400000}



